"use strict";
var myString;
var myNum;
var myBool;
var myVar;
/*
let strArray: string[];
let numArray: number[];
let boolArray: boolean[];
*/
var strArray;
var numArray;
var boolArray;
var strNumTuple;
myString = "Hello" + " " + "World";
myNum = 22;
myBool = true;
myVar = "Hello".slice(0, 3);
strArray = ["Hello", "World"];
numArray = [1, 2, 3];
boolArray = [true, false, false];
strNumTuple = ["Hello", 4];
var myVoid = undefined;
var myNull = null;
var myUndefined = undefined;
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(myVar);
console.log(strArray);
console.log(numArray);
console.log(boolArray);
console.log(strNumTuple);
console.log(myVoid);
